apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vfr-outlook
  namespace: vfr-outlook
  annotations:
    metallb.universe.tf/address-pool: pool
    traefik.ingress.kubernetes.io/router.observability.tracing: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: vfr.broken-top.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vfr-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vfr-frontend
                port:
                  number: 80
